http:
  services:
    api:
      loadBalancer:
        servers:
          - url: "http://meeting_api:3000"
          # - url: "http://api-meeting-backend:3000"
    app:
      loadBalancer:
        servers:
          - url: "http://meeting_app:5173"
          # - url: "http://app-meeting-backend:5173"
  routers:
    api:
      rule: Host(`app.goldgod.xyz`) && PathPrefix(`/api`)
      service: api #@docker #:3000
      # tls:
      #   certResolver: myresolver # 不必，使用websecure的tls
      entryPoints: 
        - websecure
      # middlewares:
      #   - traefik-auth
    app:
      rule: Host(`app.goldgod.xyz`)
      service: app #@docker #:5173
      entryPoints: 
        - websecure
