http:
  services:
    phpmyadmin:
      loadBalancer:
        servers:
          - url: "http://meeting_phpmyadmin:80"
          # - url: "http://phpmyadmin-meeting-backend:80"
  routers:
    phpmyadmin:
      rule: Host(`db.aijsts.com`)
      service: phpmyadmin #@docker #:80
      entryPoints: 
        - websecure
      middlewares:
        - mysql-auth
  middlewares:
    mysql-auth:
      digestAuth:
        usersFile: "/var/run/secrets/mysql/users"
        realm: "traefik"
        headerField: X-WebAuth-User
        removeHeader: false
